### ISSUE TITLE
Unexpected debug output

### ISSUE THREAD

**Issue by Sindbad6** [BenGig/MMM-Departures#4]
I get unexpected debug output, even if debug is switched off:
`MMM-Departures error:`

I use 
Magicmirror 2.1.1
Node 7.4

The part of the config looks like this:

`{
    			module: 'MMM-Departures',
    			position: 'top_center',
    			config: {
					debug: false,
      					provider: 'Nvv',	// 'Bahn',
      					maxElements: 5,
      					absoluteTime: false,
					updateInterval: 15,
      					stations: [
							{
          							stationName: 'Heideweg',
          							stationId: "2200193",
          							hideBelow: 3,
        						},
        						{
          							stationName: 'Marbachshöhe',
          							stationId: '2200247',
          							hideBelow: 12,
        						},		
      						],
    				},
  		},`

**Comment by BenGig** [comment]
Got it: the common time unit for updates is milliseconds, i.e. in calendar or currentweather. The config has an update interval of 15 milliseconds. 
While I would say this is not the unit we are used to, I want to stick with the standard.

**Comment by Sindbad6** [comment]
Shall I change the setting to 15 * 60 * 1000?

**Comment by BenGig** [comment]
Yes. I looked in several modules, all calculate like this.

I will point this out clearer in the documentation later.
