### ISSUE TITLE
Openshift V2 End of Life

### ISSUE THREAD

**Issue by sbiermann** [BenGig/MMM-Departures#8]
Hallo,
der REST-Service den du nutzt (transportrest-sbiermann.rhcloud.com) muss von der Openshift Plattform umziehen, da die Openshift V2 Plattform eingestellt wird. 
Ich habe im FHEM Forum ein Diskussionsbeitrag zum ursprünglichen Tablet-UI Modul gemacht: https://forum.fhem.de/index.php/topic,48255.msg677416.html#msg677416

Viele Grüße
Stefan

**Comment by BenGig** [comment]
Danke für die Nachricht, ich kommentier im FHEM-Forum.
